const products = [
    { 
      id: 1, 
      name: 'Organic Bananas', 
      quantity: '7pcs, Priceg', 
      price: 4.99, 
      image: '🍌', 
      weight: '12kg, Price',
      description: 'Bananas are nutritious. Bananas may be good for weight loss. Bananas may be good for your heart. As part of a healthy and varied diet.',
      nutrition: '100gr',
      rating: 4.5,
      reviews: 28
    },
    { 
      id: 2, 
      name: 'Red Apple', 
      quantity: '1kg, Priceg', 
      price: 4.99, 
      image: '🍎', 
      weight: '1kg, Price',
      description: 'Apples are nutritious. Apples may be good for weight loss. Apples may be good for your heart. As part of a healthy and varied diet.',
      nutrition: '100gr',
      rating: 5,
      reviews: 45
    },
    { 
      id: 3, 
      name: 'Fresh Tomatoes', 
      quantity: '1kg', 
      price: 3.99, 
      image: '🍅', 
      weight: '1kg, Price',
      description: 'Tomatoes are nutritious. Tomatoes may be good for weight loss. Rich in vitamins and antioxidants.',
      nutrition: '100gr',
      rating: 4,
      reviews: 32
    },
    { 
      id: 4, 
      name: 'Cauliflower', 
      quantity: '1pc', 
      price: 2.99, 
      image: '🥬', 
      weight: '1pc, Price',
      description: 'Fresh cauliflower is a great source of fiber and vitamins. Perfect for healthy cooking.',
      nutrition: '100gr',
      rating: 4.5,
      reviews: 18
    },
    { 
      id: 5, 
      name: 'Bell Pepper Red', 
      quantity: '1kg, Price', 
      price: 4.99, 
      image: '🫑', 
      weight: '1kg, Price',
      description: 'Red bell peppers are sweet and crunchy. High in vitamin C and antioxidants.',
      nutrition: '100gr',
      rating: 4.8,
      reviews: 52
    },
    { 
      id: 6, 
      name: 'Egg Chicken Red', 
      quantity: '4pcs, Price', 
      price: 1.99, 
      image: '🥚', 
      weight: '4pcs, Price',
      description: 'Fresh farm eggs. High in protein and essential nutrients. Perfect for breakfast.',
      nutrition: '100gr',
      rating: 4.7,
      reviews: 89
    },
    { 
      id: 7, 
      name: 'Ginger', 
      quantity: '250gm, Price', 
      price: 2.99, 
      image: '🫚', 
      weight: '250gm, Price',
      description: 'Fresh ginger root. Great for cooking and health benefits. Anti-inflammatory properties.',
      nutrition: '100gr',
      rating: 4.3,
      reviews: 24
    },
    { 
      id: 8, 
      name: 'Fresh Carrots', 
      quantity: '1kg', 
      price: 2.49, 
      image: '🥕', 
      weight: '1kg, Price',
      description: 'Crispy fresh carrots. Rich in beta carotene and fiber. Great for snacking.',
      nutrition: '100gr',
      rating: 4.6,
      reviews: 41
    },
    { 
      id: 9, 
      name: 'Green Lettuce', 
      quantity: '1pc', 
      price: 1.99, 
      image: '🥬', 
      weight: '1pc, Price',
      description: 'Fresh green lettuce. Perfect for salads. Low in calories and high in nutrients.',
      nutrition: '100gr',
      rating: 4.2,
      reviews: 15
    },
    { 
      id: 10, 
      name: 'Orange Juice', 
      quantity: '1L', 
      price: 3.49, 
      image: '🍊', 
      weight: '1L, Price',
      description: 'Fresh squeezed orange juice. Rich in vitamin C. No added sugar.',
      nutrition: '100ml',
      rating: 4.9,
      reviews: 67
    },
  ];